<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
   <testsuite name="TestAssets.Smoke_tst"
               tests="51"
               id="1"
               package=""
               time="9.569"
               hostname="CD-LYAO-02"
               timestamp="2024-03-28T16:07:11"
               failures="51"
               errors="0">
      <properties/>
      <testcase name="Test Suite: Test Suite/Test Suite: Initialize ParaBank/Test 1: Login to initialize"
                 classname="TestAssets.Smoke_tst"
                 time="0.324"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Connection refused: connect" type="Failure">A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore/Test 1: Check BookStore WSDL"
                 classname="TestAssets.Smoke_tst"
                 time="0.052"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Connection refused: connect" type="Failure">A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore/Test 2: getItemById"
                 classname="TestAssets.Smoke_tst"
                 time="0.336"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore/Test 3: getItemByTitle"
                 classname="TestAssets.Smoke_tst"
                 time="0.056"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Username Token/Test Suite: SearchBooks/Test 1: getItemByTitle(string)[Auth Data (row 1)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.086"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Auth Data (row 1): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Auth Data (row 1): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Username Token/Test Suite: SearchBooks/Test 1: getItemByTitle(string)[Auth Data (row 2)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.064"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Auth Data (row 2): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Auth Data (row 2): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Username Token/Test Suite: SearchBooks/Test 1: getItemByTitle(string)[Auth Data (row 3)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.055"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Auth Data (row 3): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Auth Data (row 3): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Username Token/Test Suite: SearchBooks/Test 1: getItemByTitle(string)[Auth Data (row 4)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.061"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Auth Data (row 4): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Auth Data (row 4): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Username Token/Test Suite: SearchBooks/Test 1: getItemByTitle(string)[Auth Data (row 5)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.069"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Auth Data (row 5): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Auth Data (row 5): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Username Token/Test Suite: SearchBooks/Test 1: getItemByTitle(string)[Auth Data (row 6)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.044"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Auth Data (row 6): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Auth Data (row 6): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Username Token/Test Suite: SearchBooks/Test 1: getItemByTitle(string)[Auth Data (row 7)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.065"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Auth Data (row 7): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Auth Data (row 7): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Username Token/Test Suite: SearchBooks/Test 2: getItemById(int)"
                 classname="TestAssets.Smoke_tst"
                 time="0.046"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 1)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.851"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Orders by IDs (row 1): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Orders by IDs (row 1): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 2)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.124"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Orders by IDs (row 2): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Orders by IDs (row 2): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 3)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.129"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Orders by IDs (row 3): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Orders by IDs (row 3): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 4)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.075"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Orders by IDs (row 4): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Orders by IDs (row 4): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 5)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.092"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Orders by IDs (row 5): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Orders by IDs (row 5): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 6)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.110"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Orders by IDs (row 6): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Orders by IDs (row 6): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 7)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.074"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Orders by IDs (row 7): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Orders by IDs (row 7): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Signature/Test 2: getItemsInCart"
                 classname="TestAssets.Smoke_tst"
                 time="0.085"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Signature/Test 3: submitOrder"
                 classname="TestAssets.Smoke_tst"
                 time="0.065"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 1)]"
                 classname="TestAssets.Smoke_tst"
                 time="1.200"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Orders by IDs (row 1): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Orders by IDs (row 1): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 2)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.044"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Orders by IDs (row 2): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Orders by IDs (row 2): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 3)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.064"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Orders by IDs (row 3): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Orders by IDs (row 3): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 4)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.062"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Orders by IDs (row 4): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Orders by IDs (row 4): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 5)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.053"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Orders by IDs (row 5): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Orders by IDs (row 5): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 6)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.059"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Orders by IDs (row 6): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Orders by IDs (row 6): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 7)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.064"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Orders by IDs (row 7): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Orders by IDs (row 7): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption/Test 2: getItemsInCart"
                 classname="TestAssets.Smoke_tst"
                 time="0.053"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption/Test 3: submitOrder"
                 classname="TestAssets.Smoke_tst"
                 time="0.065"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption and Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 1)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.115"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Orders by IDs (row 1): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Orders by IDs (row 1): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption and Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 2)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.106"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Orders by IDs (row 2): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Orders by IDs (row 2): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption and Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 3)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.143"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Orders by IDs (row 3): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Orders by IDs (row 3): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption and Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 4)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.152"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Orders by IDs (row 4): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Orders by IDs (row 4): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption and Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 5)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.114"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Orders by IDs (row 5): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Orders by IDs (row 5): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption and Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 6)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.147"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Orders by IDs (row 6): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Orders by IDs (row 6): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption and Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 7)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.131"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: Orders by IDs (row 7): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: Orders by IDs (row 7): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption and Signature/Test 2: getItemsInCart"
                 classname="TestAssets.Smoke_tst"
                 time="0.126"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption and Signature/Test 3: submitOrder"
                 classname="TestAssets.Smoke_tst"
                 time="0.116"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: ParaBank/Test 1: Check ParaBank WSDL"
                 classname="TestAssets.Smoke_tst"
                 time="0.024"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Connection refused: connect" type="Failure">A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: ParaBank/Test 2: getAccount"
                 classname="TestAssets.Smoke_tst"
                 time="0.033"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: ParaBank/Test 3: getCustomer"
                 classname="TestAssets.Smoke_tst"
                 time="0.039"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: LoanProcessor/Test 1: Check LoanProcessor WSDL"
                 classname="TestAssets.Smoke_tst"
                 time="0.017"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Connection refused: connect" type="Failure">A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: LoanProcessor/Test 2: requestLoan"
                 classname="TestAssets.Smoke_tst"
                 time="0.035"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: REST/Test Suite: ParaBank/Test 1: Check OpenAPI"
                 classname="TestAssets.Smoke_tst"
                 time="0.024"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Connection refused: connect" type="Failure">A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: REST/Test Suite: ParaBank/Test Suite: /accounts/{accountId}/Test 1: /accounts/{accountId} - GET"
                 classname="TestAssets.Smoke_tst"
                 time="0.816"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

Invalid OpenAPI/Swagger definition at http://localhost:8080/parabank/services/bank/swagger.json
java.io.IOException: Invalid OpenAPI/Swagger definition at http://localhost:8080/parabank/services/bank/swagger.json&#xD;
	at com.parasoft.rest.swagger.SwaggerDefinition.buildOpenAPI(SwaggerDefinition.java:124)&#xD;
	at com.parasoft.rest.swagger.SwaggerDefinition.readSwagger(SwaggerDefinition.java:84)&#xD;
	at webtool.messaging.rest.RestDefinitionManagerImpl.getDefinition(RestDefinitionManagerImpl.java:55)&#xD;
	at webtool.soap.SOAPPlugIn.getDefinition(SOAPPlugIn.java:868)&#xD;
	at webtool.soap.http.RESTClient.getDefinition(RESTClient.java:890)&#xD;
	at webtool.soap.http.RESTClient.doUpdateFromDefinition(RESTClient.java:909)&#xD;
	at webtool.soap.http.RESTClient.updateFromDefinition(RESTClient.java:903)&#xD;
	at webtool.soap.http.RESTClient.beginBatch(RESTClient.java:190)&#xD;
	at webtool.test.ToolTest.run(ToolTest.java:846)&#xD;
	at webtool.soap.http.HTTPClientToolTest.run(HTTPClientToolTest.java:70)&#xD;
	at webtool.soap.http.RESTClientToolTest.run(RESTClientToolTest.java:47)&#xD;
	at webtool.test.Test$4.loop(Test.java:943)&#xD;
	at webtool.test.execution.CompositeExecutionLoop.loop(CompositeExecutionLoop.java:60)&#xD;
	at webtool.test.execution.CompositeExecutionLoop.loop(CompositeExecutionLoop.java:69)&#xD;
	at webtool.test.execution.CompositeExecutionLoop.loop(CompositeExecutionLoop.java:69)&#xD;
	at webtool.test.execution.CompositeExecutionLoop.loop(CompositeExecutionLoop.java:69)&#xD;
	at webtool.test.execution.CompositeExecutionLoop.loop(CompositeExecutionLoop.java:69)&#xD;
	at webtool.test.execution.CompositeExecutionLoop.loop(CompositeExecutionLoop.java:69)&#xD;
	at webtool.test.execution.CompositeExecutionLoop.loop(CompositeExecutionLoop.java:69)&#xD;
	at webtool.test.execution.CompositeExecutionLoop.loop(CompositeExecutionLoop.java:69)&#xD;
	at webtool.test.Test.run(Test.java:1105)&#xD;
	at webtool.test.TestExecutor.run(TestExecutor.java:241)&#xD;
	at com.parasoft.ptest.testcases.web.WebTestExecution.doRun(WebTestExecution.java:75)&#xD;
	at com.parasoft.ptest.testcases.web.AbstractWebTestRunnable.runSingleTest(AbstractWebTestRunnable.java:308)&#xD;
	at com.parasoft.ptest.testcases.web.AbstractWebTestRunnable.run(AbstractWebTestRunnable.java:177)&#xD;
	at com.parasoft.ptest.execution.api.web.WebExecutionRunnable.launch(WebExecutionRunnable.java:594)&#xD;
	at com.parasoft.ptest.execution.api.runnable.AbstractExecutionRunnable.launch(AbstractExecutionRunnable.java:424)&#xD;
	at com.parasoft.ptest.execution.api.runnable.AbstractExecutionRunnable.runExecution(AbstractExecutionRunnable.java:284)&#xD;
	at com.parasoft.ptest.execution.api.runnable.AbstractExecutionRunnable.run0(AbstractExecutionRunnable.java:174)&#xD;
	at com.parasoft.ptest.checkers.api.run.AbstractRunnable.run(AbstractRunnable.java:213)&#xD;
	at com.parasoft.ptest.checkers.api.run.CategoryRunnable.run(CategoryRunnable.java:254)&#xD;
	at com.parasoft.ptest.checkers.api.run.ConfigRunner.runCheckerCategories(ConfigRunner.java:399)&#xD;
	at com.parasoft.ptest.checkers.api.run.ConfigRunner.runConfig(ConfigRunner.java:231)&#xD;
	at com.parasoft.ptest.checkers.api.cli8.AbstractCliRunnable.runConfig(AbstractCliRunnable.java:869)&#xD;
	at com.parasoft.ptest.checkers.api.cli8.AbstractCliRunnable.run(AbstractCliRunnable.java:450)&#xD;
	at com.parasoft.ptest.checkers.api.cli8.AbstractCliRunnable.run(AbstractCliRunnable.java:255)&#xD;
	at com.parasoft.ptest.testcases.eclipse.core.web.internal.cli.EclipseWebTestCliRunnable.run(EclipseWebTestCliRunnable.java:80)&#xD;
	at com.parasoft.ptest.checkers.eclipse.core.cli8.EclipseCliRunnable.start(EclipseCliRunnable.java:133)&#xD;
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)&#xD;
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)&#xD;
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)&#xD;
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)&#xD;
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)&#xD;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#xD;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#xD;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#xD;
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)&#xD;
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)&#xD;
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)&#xD;
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)&#xD;
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: REST/Test Suite: ParaBank/Test Suite: /customers/{customerId}/Test 1: /customers/{customerId} - GET"
                 classname="TestAssets.Smoke_tst"
                 time="0.050"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

Invalid OpenAPI/Swagger definition at http://localhost:8080/parabank/services/bank/swagger.json
java.io.IOException: Invalid OpenAPI/Swagger definition at http://localhost:8080/parabank/services/bank/swagger.json&#xD;
	at com.parasoft.rest.swagger.SwaggerDefinition.buildOpenAPI(SwaggerDefinition.java:124)&#xD;
	at com.parasoft.rest.swagger.SwaggerDefinition.readSwagger(SwaggerDefinition.java:84)&#xD;
	at webtool.messaging.rest.RestDefinitionManagerImpl.getDefinition(RestDefinitionManagerImpl.java:55)&#xD;
	at webtool.soap.SOAPPlugIn.getDefinition(SOAPPlugIn.java:868)&#xD;
	at webtool.soap.http.RESTClient.getDefinition(RESTClient.java:890)&#xD;
	at webtool.soap.http.RESTClient.doUpdateFromDefinition(RESTClient.java:909)&#xD;
	at webtool.soap.http.RESTClient.updateFromDefinition(RESTClient.java:903)&#xD;
	at webtool.soap.http.RESTClient.beginBatch(RESTClient.java:190)&#xD;
	at webtool.test.ToolTest.run(ToolTest.java:846)&#xD;
	at webtool.soap.http.HTTPClientToolTest.run(HTTPClientToolTest.java:70)&#xD;
	at webtool.soap.http.RESTClientToolTest.run(RESTClientToolTest.java:47)&#xD;
	at webtool.test.Test$4.loop(Test.java:943)&#xD;
	at webtool.test.execution.CompositeExecutionLoop.loop(CompositeExecutionLoop.java:60)&#xD;
	at webtool.test.execution.CompositeExecutionLoop.loop(CompositeExecutionLoop.java:69)&#xD;
	at webtool.test.execution.CompositeExecutionLoop.loop(CompositeExecutionLoop.java:69)&#xD;
	at webtool.test.execution.CompositeExecutionLoop.loop(CompositeExecutionLoop.java:69)&#xD;
	at webtool.test.execution.CompositeExecutionLoop.loop(CompositeExecutionLoop.java:69)&#xD;
	at webtool.test.execution.CompositeExecutionLoop.loop(CompositeExecutionLoop.java:69)&#xD;
	at webtool.test.execution.CompositeExecutionLoop.loop(CompositeExecutionLoop.java:69)&#xD;
	at webtool.test.execution.CompositeExecutionLoop.loop(CompositeExecutionLoop.java:69)&#xD;
	at webtool.test.Test.run(Test.java:1105)&#xD;
	at webtool.test.TestExecutor.run(TestExecutor.java:241)&#xD;
	at com.parasoft.ptest.testcases.web.WebTestExecution.doRun(WebTestExecution.java:75)&#xD;
	at com.parasoft.ptest.testcases.web.AbstractWebTestRunnable.runSingleTest(AbstractWebTestRunnable.java:308)&#xD;
	at com.parasoft.ptest.testcases.web.AbstractWebTestRunnable.run(AbstractWebTestRunnable.java:177)&#xD;
	at com.parasoft.ptest.execution.api.web.WebExecutionRunnable.launch(WebExecutionRunnable.java:594)&#xD;
	at com.parasoft.ptest.execution.api.runnable.AbstractExecutionRunnable.launch(AbstractExecutionRunnable.java:424)&#xD;
	at com.parasoft.ptest.execution.api.runnable.AbstractExecutionRunnable.runExecution(AbstractExecutionRunnable.java:284)&#xD;
	at com.parasoft.ptest.execution.api.runnable.AbstractExecutionRunnable.run0(AbstractExecutionRunnable.java:174)&#xD;
	at com.parasoft.ptest.checkers.api.run.AbstractRunnable.run(AbstractRunnable.java:213)&#xD;
	at com.parasoft.ptest.checkers.api.run.CategoryRunnable.run(CategoryRunnable.java:254)&#xD;
	at com.parasoft.ptest.checkers.api.run.ConfigRunner.runCheckerCategories(ConfigRunner.java:399)&#xD;
	at com.parasoft.ptest.checkers.api.run.ConfigRunner.runConfig(ConfigRunner.java:231)&#xD;
	at com.parasoft.ptest.checkers.api.cli8.AbstractCliRunnable.runConfig(AbstractCliRunnable.java:869)&#xD;
	at com.parasoft.ptest.checkers.api.cli8.AbstractCliRunnable.run(AbstractCliRunnable.java:450)&#xD;
	at com.parasoft.ptest.checkers.api.cli8.AbstractCliRunnable.run(AbstractCliRunnable.java:255)&#xD;
	at com.parasoft.ptest.testcases.eclipse.core.web.internal.cli.EclipseWebTestCliRunnable.run(EclipseWebTestCliRunnable.java:80)&#xD;
	at com.parasoft.ptest.checkers.eclipse.core.cli8.EclipseCliRunnable.start(EclipseCliRunnable.java:133)&#xD;
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)&#xD;
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)&#xD;
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)&#xD;
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)&#xD;
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)&#xD;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#xD;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#xD;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#xD;
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)&#xD;
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)&#xD;
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)&#xD;
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)&#xD;
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: Web/Test 1: Front Page"
                 classname="TestAssets.Smoke_tst"
                 time="0.733"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Connection refused: connect" type="Failure">A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: JMS/Test Suite: LoanProcessor/Test 1: Request Loan JMS"
                 classname="TestAssets.Smoke_tst"
                 time="1.355"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Could not connect to broker URL: tcp://localhost:61616. Reason: java.net.ConnectException: Connection refused: connect"
                   type="Failure">javax.jms.JMSException: Could not connect to broker URL: tcp://localhost:61616. Reason: java.net.ConnectException: Connection refused: connect&#xD;
	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:49)&#xD;
	at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:419)&#xD;
	at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:349)&#xD;
	at org.apache.activemq.ActiveMQConnectionFactory.createQueueConnection(ActiveMQConnectionFactory.java:262)&#xD;
	at webtool.messaging.JMSConnectionUtil.createQueueConnection(JMSConnectionUtil.java:65)&#xD;
	at webtool.soap.jms.JMS10Sender.init(JMS10Sender.java:87)&#xD;
	at webtool.soap.jms.JMS10Sender.invoke(JMS10Sender.java:183)&#xD;
	at webtool.soap.jms.JMSSender.invoke(JMSSender.java:156)&#xD;
	at webtool.messaging.MessagingClientConfig.invokeOverTransportSender(MessagingClientConfig.java:324)&#xD;
	at webtool.messaging.MessagingClientConfig.invoke(MessagingClientConfig.java:145)&#xD;
	at webtool.messaging.MessagingClientConfig.invoke(MessagingClientConfig.java:134)&#xD;
	at webtool.messaging.MessageRunner.call(MessageRunner.java:49)&#xD;
	at webtool.messaging.MessageRunner.call(MessageRunner.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
Caused by: java.net.ConnectException: Connection refused: connect&#xD;
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)&#xD;
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)&#xD;
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:615)&#xD;
	at org.apache.activemq.transport.tcp.TcpTransport.connect(TcpTransport.java:525)&#xD;
	at org.apache.activemq.transport.tcp.TcpTransport.doStart(TcpTransport.java:488)&#xD;
	at org.apache.activemq.util.ServiceSupport.start(ServiceSupport.java:55)&#xD;
	at org.apache.activemq.transport.AbstractInactivityMonitor.start(AbstractInactivityMonitor.java:172)&#xD;
	at org.apache.activemq.transport.InactivityMonitor.start(InactivityMonitor.java:52)&#xD;
	at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)&#xD;
	at org.apache.activemq.transport.WireFormatNegotiator.start(WireFormatNegotiator.java:72)&#xD;
	at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)&#xD;
	at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)&#xD;
	at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:399)&#xD;
	... 15 more&#xD;
[Nested Exception] java.net.ConnectException: Connection refused: connect&#xD;
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)&#xD;
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)&#xD;
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:615)&#xD;
	at org.apache.activemq.transport.tcp.TcpTransport.connect(TcpTransport.java:525)&#xD;
	at org.apache.activemq.transport.tcp.TcpTransport.doStart(TcpTransport.java:488)&#xD;
	at org.apache.activemq.util.ServiceSupport.start(ServiceSupport.java:55)&#xD;
	at org.apache.activemq.transport.AbstractInactivityMonitor.start(AbstractInactivityMonitor.java:172)&#xD;
	at org.apache.activemq.transport.InactivityMonitor.start(InactivityMonitor.java:52)&#xD;
	at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)&#xD;
	at org.apache.activemq.transport.WireFormatNegotiator.start(WireFormatNegotiator.java:72)&#xD;
	at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)&#xD;
	at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)&#xD;
	at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:399)&#xD;
	at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:349)&#xD;
	at org.apache.activemq.ActiveMQConnectionFactory.createQueueConnection(ActiveMQConnectionFactory.java:262)&#xD;
	at webtool.messaging.JMSConnectionUtil.createQueueConnection(JMSConnectionUtil.java:65)&#xD;
	at webtool.soap.jms.JMS10Sender.init(JMS10Sender.java:87)&#xD;
	at webtool.soap.jms.JMS10Sender.invoke(JMS10Sender.java:183)&#xD;
	at webtool.soap.jms.JMSSender.invoke(JMSSender.java:156)&#xD;
	at webtool.messaging.MessagingClientConfig.invokeOverTransportSender(MessagingClientConfig.java:324)&#xD;
	at webtool.messaging.MessagingClientConfig.invoke(MessagingClientConfig.java:145)&#xD;
	at webtool.messaging.MessagingClientConfig.invoke(MessagingClientConfig.java:134)&#xD;
	at webtool.messaging.MessageRunner.call(MessageRunner.java:49)&#xD;
	at webtool.messaging.MessageRunner.call(MessageRunner.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: DB/Test Suite: BookStore/Test 1: Books"
                 classname="TestAssets.Smoke_tst"
                 time="0.687"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">Changed element name from the expected "resultSet" to "SQLException" in XPath /results/resultSet
Expected element tag name 'resultSet' but was 'SQLException' - comparing &lt;resultSet...&gt; at /results[1]/resultSet[1] to &lt;SQLException...&gt; at /results[1]/SQLException[1]
Source: text

Changed element type from "Element" to "Text" in XPath /results/resultSet/rows
Expected node type '1' but was '3' - comparing &lt;rows...&gt; at /results[1]/resultSet[1]/rows[1] to &lt;SQLException ...&gt;java.sql.SQLException: Unable to instantiate class "org.hsqldb.jdbcDriver". Please check the DB driver classname and the jar file locations in Parasoft &gt; Preferences &gt; JDBC Drivers.&lt;/SQLException&gt; at /results[1]/SQLException[1]/text()[1]
Source: text

Deleted element at XPath /results/resultSet/rows/row[1]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[1] to  at null
Source: text

Deleted element at XPath /results/resultSet/rows/row[2]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[2] to  at null
Source: text

Deleted element at XPath /results/resultSet/rows/row[3]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[3] to  at null
Source: text

Deleted element at XPath /results/resultSet/rows/row[4]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[4] to  at null
Source: text

Deleted element at XPath /results/resultSet/rows/row[5]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[5] to  at null
Source: text

Deleted element at XPath /results/resultSet/rows/row[6]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[6] to  at null
Source: text

Deleted element at XPath /results/resultSet/rows/row[7]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[7] to  at null
Source: text

Deleted element at XPath /results/resultSet/rows/row[8]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[8] to  at null
Source: text

Deleted element at XPath /results/resultSet/rows/row[9]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[9] to  at null
Source: text</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: DB/Test Suite: ParaBank/Test 1: Customers"
                 classname="TestAssets.Smoke_tst"
                 time="0.079"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">Changed element name from the expected "resultSet" to "SQLException" in XPath /results/resultSet
Expected element tag name 'resultSet' but was 'SQLException' - comparing &lt;resultSet...&gt; at /results[1]/resultSet[1] to &lt;SQLException...&gt; at /results[1]/SQLException[1]
Source: text

Changed element type from "Element" to "Text" in XPath /results/resultSet/rows
Expected node type '1' but was '3' - comparing &lt;rows...&gt; at /results[1]/resultSet[1]/rows[1] to &lt;SQLException ...&gt;java.sql.SQLException: Unable to instantiate class "org.hsqldb.jdbcDriver". Please check the DB driver classname and the jar file locations in Parasoft &gt; Preferences &gt; JDBC Drivers.&lt;/SQLException&gt; at /results[1]/SQLException[1]/text()[1]
Source: text

Deleted element at XPath /results/resultSet/rows/row[1]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[1] to  at null
Source: text

Deleted element at XPath /results/resultSet/rows/row[2]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[2] to  at null
Source: text</failure>
      </testcase>
      <system-out/>
      <system-err/>
   </testsuite>
</testsuites>
